/*
 * Tanque.java
 */
package net.ausiasmarch.tanque.modelo;

/**
 * Clase que representa un Tanque de agua
 * @author  Luis
 */
public class Tanque extends javax.swing.JPanel {

   
    /**
     * Crea un tanque de agua
     */
    EstadoTanque estado;

    public EstadoTanque getEstado() {
        return estado;
    }
    
    
    
    public Tanque() {
        initComponents();

      
    }
    /**
        * Metodo para llenar el tanque por la mitad
        */
    public void llenarMedio(){
        switch(estado){
            case VACIO:
                estado = EstadoTanque.VACIO;
                jLabelMedio.setVisible(true);
                jLabelVacio.setVisible(false);
                jLabelLleno.setVisible(false);
                break;
            case MEDIO:
                estado = EstadoTanque.MEDIO;
                jLabelLleno.setVisible(true);
                jLabelMedio.setVisible(false);
                jLabelVacio.setVisible(false);
        }    
    }
     
    public void vaciarMedio(){
        switch(estado){
            case LLENO:
                estado = EstadoTanque.LLENO;
                jLabelMedio.setVisible(true);
                jLabelVacio.setVisible(false);
                jLabelLleno.setVisible(false);
                break;
            case MEDIO:
                estado = EstadoTanque.MEDIO;
                jLabelVacio.setVisible(true);
                jLabelMedio.setVisible(false);
                jLabelLleno.setVisible(false);
        }
    }
    
    
    
    
    
    
    

    
     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLleno = new javax.swing.JLabel();
        jLabelMedio = new javax.swing.JLabel();
        jLabelVacio = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/tanque/img/Lleno.png"))); // NOI18N
        add(jLabelLleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelMedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/tanque/img/Medio.png"))); // NOI18N
        add(jLabelMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelVacio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/tanque/img/Vacio.png"))); // NOI18N
        add(jLabelVacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLleno;
    private javax.swing.JLabel jLabelMedio;
    private javax.swing.JLabel jLabelVacio;
    // End of variables declaration//GEN-END:variables
}
